---
abstract: 'Identify requirements for a distribution'
author:
  - 'Jeffrey Ryan Thalhammer <jeff@imaginative-software.com>'
build_requires:
  File::Basename: 0
  File::Find: 0
  File::Spec: 0
  FindBin: 0
  Module::Build: 0.3601
  Test::More: 0
  Test::Most: 0
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Requires
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Dist::Requires:
    file: lib/Dist/Requires.pm
    version: 0.005
requires:
  Archive::Extract: 0
  CPAN::Meta: 0
  Carp: 0
  Cwd: 0
  ExtUtils::MakeMaker: 6.58
  File::Temp: 0
  IPC::Run: 0
  Module::Build: 0.21
  Module::CoreList: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  Path::Class: 0
  namespace::autoclean: 0
  perl: 5.006
  version: 0
resources:
  bugtracker: https://github.com/thaljef/Dist-Requires/issues
  repository: git://github.com/thaljef/Dist-Requires.git
version: 0.005
